services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS:--encoding=UTF8 --locale=C}
    volumes:
      - ./postgres_data:/var/lib/postgresql
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - postgres-network

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: unless-stopped
#    ports:
#      - 15433:80
#    env_file:
#      - .env
#    depends_on:
#      postgres:
#        condition: service_healthy
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
#  pgadmin_data:
