services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      JAVA_OPTS_KC_HEAP: >
        -XX:InitialRAMPercentage=35
        -XX:MaxRAMPercentage=60
        -XX:MinHeapFreeRatio=20
        -XX:MaxHeapFreeRatio=30

    mem_limit: 1500m
    command: start-dev
    volumes:
      - ./keycloak/themes:/opt/keycloak/themes
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\n\r\n' >&3 && grep '200 OK' <&3" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

